apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress
spec:
  interval: 5m0s
  path: ./infrastructure/minikube/ingress
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system