apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tenant-app
spec:
  interval: 10s
  ref:
    branch: main
  secretRef:
    name: git-repo-credentials
  url: ssh://git@github.com/kim-ae/tenant-app.flux-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenant-app
spec:
  interval: 10s
  prune: true
  serviceAccountName: tenant-app
  sourceRef:
    kind: GitRepository
    name: tenant-app