apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tenant-app
resources:
  - namespace.yaml
  - rbac.yaml
  - kustomization.flux.yaml

commonLabels:
  toolkit.fluxcd.io/tenant: tenant-app