apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenant-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-app-reconciler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: gotk:tenant-app:reconciler
  - kind: ServiceAccount
    name: tenant-app
    namespace: tenant-app