apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  interval: 15s
  path: ./namespaces/minikube
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system