namespace: awesome-system
resources:
  - ../../base/awesome-system
  - git-repo-credentials.sealed.yaml
patches:
  - path: kustomization.flux.patch.yaml

commonLabels:
  toolkit.fluxcd.io/tenant: awesome-system