apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: roles
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure/minikube/roles
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system