apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: infrastructure
spec:
  interval: 24h
  url: https://bitnami-labs.github.io/sealed-secrets
